{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "recipiebook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "recipiebook.name" . }}
    chart: {{ template "recipiebook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  admin-user: {{ .Values.adminUser | b64enc | quote }}
  {{- if .Values.adminPassword }}
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- if .Values.adminEmail }}
  admin-email: {{ .Values.adminEmail | b64enc | quote }}
  {{- else }}
  admin-email: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
{{- end }}
