# Generated by Django 2.2.5 on 2019-09-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_item_itemlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Itemlist',
            new_name='itemlist',
        ),
    ]
