# Generated by Django 2.2.5 on 2019-09-08 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_auto_20190908_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoppingitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.Recipie')),
            ],
        ),
    ]
