# Generated by Django 2.2.5 on 2019-09-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
